spring.application.name=sundayschool
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tmcf_sunday_school
spring.datasource.username=root
spring.datasource.password=Tony

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=TMCF_Sunday_School_Secret_Key_2026_Very_Long_And_Secure_256bit
jwt.expiration=86400000
